## Carga de librerias

In [2]:
import pandas as pd
import geopandas as gpd

In [3]:
ruta_csv = "../datos/crudos"

In [4]:
ruta_shp = "../datos/crudos/insumos/"

In [5]:
datos_insumos = pd.read_csv(ruta_csv+"/origendatos.csv")

In [6]:
datos_insumos

,nombre,origen,variable
0,ifraestructura vial ciclista,https://datos.cdmx.gob.mx/dataset/infraestruc...,proximidad
1,lineas y estaciones de metro,https://datos.cdmx.gob.mx/dataset/lineas-y-es...,proximidad
2,Ubicación de líneas y estaciones del Metrobús,https://datos.cdmx.gob.mx/dataset/geolocaliza...,proximidad
3,Rutas de RTP en formato SHP,https://datos.cdmx.gob.mx/dataset/e5e67126-89...,proximidad
4,Ubicación de líneas y estaciones/paradas del S...,https://datos.cdmx.gob.mx/dataset/geolocaliza...,proximidad
5,Ubicación de rutas del Transporte Público Conc...,https://datos.cdmx.gob.mx/dataset/ubicacion-d...,proximidad
6,Hospitales y Centros de Salud,https://datos.cdmx.gob.mx/dataset/hospitales-...,diversidad
7,Escuelas Publicas,https://datos.cdmx.gob.mx/dataset/escuelas-pu...,diversidad
8,Escuelas privadas,https://datos.cdmx.gob.mx/dataset/escuelas-pr...,diversidad
9,Áreas verdes de la Ciudad de México,https://datos.cdmx.gob.mx/dataset/cdmx_areas_...,diversidad
10,Catastro cdmx,https://sig.cdmx.gob.mx/datos/descarga#d_dato...,densidad
11,Censo de Población y Vivienda (CPV) 2020,https://www.inegi.org.mx/programas/ccpv/2020/...,densidad
12,Información vial de apoyo a la gestión del tra...,https://datos.cdmx.gob.mx/dataset/informacion...,proximidad
13,Vialidades primarias de la Ciudad de México,https://datos.cdmx.gob.mx/dataset/vialidades-...,proximidad
14,Vialidades de acceso controlado,https://datos.cdmx.gob.mx/dataset/vialidades-...,proximidad
15,Puntos de acceso WiFi en la CDMX,https://datos.cdmx.gob.mx/dataset/puntos-de-a...,digitalizacion
16,WiFi gratuito en Postes Mi Calle,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
17,WiFi gratuito en Colonias Periféricas de la CDMX,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
18,WiFi gratuito en Utopías de la CDMX,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
19,WiFi gratuito en Pilares de la CDMX,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
20,WiFi gratuito en Unidades Habitacionales de la...,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
21,WiFi gratuito en Postes del C5,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
22,WiFi gratuito en Escuelas Públicas de la CDMX,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
23,WiFi gratuito en Sitios Públicos de la CDMX,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
24,WiFi gratuito en el Transporte de la CDMX,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
25,WiFi gratuito en Centros de Salud,https://datos.cdmx.gob.mx/dataset/wifi-gratui...,digitalizacion
26,Catálogo de colonias,https://datos.cdmx.gob.mx/dataset/catalogo-de...,proximidad
27,Red de recarga externa de la Tarjeta de Movili...,https://datos.cdmx.gob.mx/dataset/red-de-reca...,proximidad
28,Datos de bicicletas (Ecobici),https://datos.cdmx.gob.mx/dataset/datos-de-bi...,proximidad
29,DIrectorio Estadístico de Unidades Económicas ...,https://datos.cdmx.gob.mx/dataset/directorio-...,diversidad

## Cargar los archivos y visualizar
### Infraestructura ciclista
#### Ciclovias

In [11]:
ciclovia = gpd.read_file(ruta_shp+ "infraestructura_vial_ciclista/Ciclovia.shp")

In [12]:
ciclovia.head()

,ID_TRAMO,ID_PROY,NOMBRE,TIPO_IC,ALCALDIA,VIALIDAD,TIPO_VIA,TIPO_CONEC,ESTADO,EJECUTOR,A_INICIO,A_TERMINO,LONG_KM,geometry
0,90,12,Reforma I,Ciclovia,Cuauhtémoc,Avenida Paseo de la Reforma,Primaria,Regional,En operacion,Gobierno Central,ND,2010,3.33,"LINESTRING Z (484275.089 2149048.861 0, 484253..."
1,91,12,Reforma I,Ciclovia,Cuauhtémoc,Avenida Paseo de la Reforma,Primaria,Regional,En operacion,Gobierno Central,ND,2010,3.16,"LINESTRING Z (481541.837 2147663.462 0, 481551..."
2,93,14,Pino Suarez,Ciclovia,Cuauhtémoc,Avenida Jose Maria Pino Suarez,Primaria,Local,Fuera de servicio,Gobierno Central,ND,2011,0.09,"LINESTRING Z (486106.093 2148589.865 0, 486103..."
3,94,14,Pino Suarez,Ciclovia,Cuauhtémoc,Avenida Jose Maria Pino Suarez,Primaria,Local,En operacion,Gobierno Central,ND,2011,0.53,"LINESTRING Z (486102.335 2148496.617 0, 486028..."
4,103,21,20 de Noviembre,Ciclovia,Cuauhtémoc,Avenida 20 de Noviembre,Primaria,Local,En operacion,Gobierno Central,ND,2012,0.66,"LINESTRING Z (485894.603 2147862.546 0, 485912..."

In [14]:
print(ciclovia.crs)

EPSG:32614

In [16]:
ciclovia.explore()

In [18]:
ciclovia_limpia = ciclovia[ciclovia["ESTADO"] == "En operacion"][
    ["ALCALDIA", "TIPO_IC", "TIPO_VIA", "TIPO_CONEC", "LONG_KM", "geometry"]
]

In [19]:
ciclovia_limpia.head()

,ALCALDIA,TIPO_IC,TIPO_VIA,TIPO_CONEC,LONG_KM,geometry
0,Cuauhtémoc,Ciclovia,Primaria,Regional,3.33,"LINESTRING Z (484275.089 2149048.861 0, 484253..."
1,Cuauhtémoc,Ciclovia,Primaria,Regional,3.16,"LINESTRING Z (481541.837 2147663.462 0, 481551..."
3,Cuauhtémoc,Ciclovia,Primaria,Local,0.53,"LINESTRING Z (486102.335 2148496.617 0, 486028..."
4,Cuauhtémoc,Ciclovia,Primaria,Local,0.66,"LINESTRING Z (485894.603 2147862.546 0, 485912..."
6,Cuauhtémoc,Ciclovia,Primaria,Local,0.53,"LINESTRING Z (484367.348 2148109.811 0, 483907..."

In [20]:
ciclovia_limpia = ciclovia_limpia.to_crs(epsg=4326)

In [21]:
ciclovia_limpia.explore()

In [22]:
ciclovia_limpia.to_file("../datos/procesados/infra_ciclista_limpia/ciclovia_limpia.gpkg", driver="GPKG")

#### Ciclovia bidireccional

In [24]:
ciclovia_bid = gpd.read_file(ruta_shp+ "infraestructura_vial_ciclista/Ciclovia bidireccional.shp")
ciclovia_bid.head()

,ID_TRAMO,ID_PROY,NOMBRE,TIPO_IC,ALCALDIA,VIALIDAD,TIPO_VIA,TIPO_CONEC,ESTADO,EJECUTOR,A_INICIO,A_TERMINO,LONG_KM,geometry
0,61,5,Ciclovía de la Ciudad de México,Ciclovia bidireccional,Miguel Hidalgo,Ciclovia de la Ciudad de Mexico,Primaria,Regional,En operacion,Gobierno Central,ND,2004,1.06,"LINESTRING Z (478124.717 2148599.047 0, 478122..."
1,62,5,Ciclovía de la Ciudad de México,Ciclovia bidireccional,Miguel Hidalgo,Ciclovia de la Ciudad de Mexico,Secundaria,Regional,En operacion,Gobierno Central,ND,2004,2.17,"LINESTRING Z (479519.771 2147008.967 0, 479506..."
2,63,5,Ciclovía de la Ciudad de México,Ciclovia bidireccional,Miguel Hidalgo,Ciclovia de la Ciudad de Mexico,De acceso controlado,Recreativa,En operacion,Gobierno Central,ND,2004,1.63,"LINESTRING Z (479805.841 2145511.313 0, 479818..."
3,64,5,Ciclovía de la Ciudad de México,Ciclovia bidireccional,Álvaro Obregón,Ciclovia de la Ciudad de Mexico,De acceso controlado,Recreativa,En operacion,Gobierno Central,ND,2004,1.23,"LINESTRING Z (480061.404 2144609.884 0, 480071..."
4,65,5,Ciclovía de la Ciudad de México,Ciclovia bidireccional,Álvaro Obregón,Ciclovia de la Ciudad de Mexico,Secundaria,Recreativa,En operacion,Gobierno Central,ND,2004,0.56,"LINESTRING Z (479610.408 2144014.092 0, 479603..."

In [25]:
ciclovia_bid.explore()

In [26]:
ciclovia_bid_limpia = ciclovia_bid[ciclovia_bid["ESTADO"] == "En operacion"][
    ["ALCALDIA", "TIPO_IC", "TIPO_VIA", "TIPO_CONEC", "LONG_KM", "geometry"]
]

In [28]:
ciclovia_bid_limpia = ciclovia_bid_limpia.to_crs(epsg=4326)

In [29]:
ciclovia_bid_limpia.to_file("../datos/procesados/infra_ciclista_limpia/ciclovia_bid_limpia.gpkg", driver="GPKG")

#### Infraestructura ciclista total

In [37]:
infra_total = gpd.read_file(ruta_shp+ "infraestructura_vial_ciclista/Infraestructura ciclista total.shp")
infra_total.head()

,ID_TRAMO,ID_PROY,NOMBRE,TIPO_IC,ALCALDIA,VIALIDAD,TIPO_VIA,TIPO_CONEC,ESTADO,EJECUTOR,A_INICIO,A_TERMINO,LONG_KM,geometry
0,1,1,Senderos Bosque de Chapultepec I Sección,Sendero compartido,Miguel Hidalgo,Gran Avenida,Secundaria,Recreativa,En operacion,Gobierno Central,ND,ND,2.04,"LINESTRING Z (481097.259 2147510.788 0, 481136..."
1,2,1,Senderos Bosque de Chapultepec I Sección,Sendero compartido,Miguel Hidalgo,Gran Avenida,Secundaria,Recreativa,En operacion,Gobierno Central,ND,ND,0.24,"LINESTRING Z (481027.993 2147542.917 0, 481050..."
2,3,1,Senderos Bosque de Chapultepec I Sección,Sendero compartido,Miguel Hidalgo,Avenida Grutas,Secundaria,Recreativa,En operacion,Gobierno Central,ND,ND,0.50,"LINESTRING Z (480740.16 2147381.202 0, 480700...."
3,4,1,Senderos Bosque de Chapultepec I Sección,Sendero compartido,Miguel Hidalgo,Calzada Mahatma Gandhi,Secundaria,Recreativa,En operacion,Gobierno Central,ND,ND,0.25,"LINESTRING Z (481050.813 2147755.562 0, 481051..."
4,5,1,Senderos Bosque de Chapultepec I Sección,Sendero compartido,Miguel Hidalgo,Avenida Juventud Heroica,Secundaria,Recreativa,En operacion,Gobierno Central,ND,ND,0.46,"LINESTRING Z (481188.261 2147428.396 0, 481249..."

In [40]:
infra_total_limpia = infra_total[infra_total["ESTADO"] == "En operacion"][
    ["ALCALDIA", "TIPO_IC", "TIPO_VIA", "TIPO_CONEC", "LONG_KM", "geometry"]
]
infra_total_limpia.head()

,ALCALDIA,TIPO_IC,TIPO_VIA,TIPO_CONEC,LONG_KM,geometry
0,Miguel Hidalgo,Sendero compartido,Secundaria,Recreativa,2.04,"LINESTRING Z (481097.259 2147510.788 0, 481136..."
1,Miguel Hidalgo,Sendero compartido,Secundaria,Recreativa,0.24,"LINESTRING Z (481027.993 2147542.917 0, 481050..."
2,Miguel Hidalgo,Sendero compartido,Secundaria,Recreativa,0.50,"LINESTRING Z (480740.16 2147381.202 0, 480700...."
3,Miguel Hidalgo,Sendero compartido,Secundaria,Recreativa,0.25,"LINESTRING Z (481050.813 2147755.562 0, 481051..."
4,Miguel Hidalgo,Sendero compartido,Secundaria,Recreativa,0.46,"LINESTRING Z (481188.261 2147428.396 0, 481249..."

In [39]:
print (infra_total_limpia.crs)

EPSG:32614

In [41]:
infra_total_limpia.to_file("../datos/procesados/infra_ciclista_limpia/infra_ciclista_limpia.gpkg", driver="GPKG")

## Lineas y estaciones del metro
En este apartado viusalizaremos los datos del metro (lineas y estaciones)

In [45]:
lineas_metro = gpd.read_file (ruta_shp + "stcmetro_shp/STC_Metro_lineas_utm14n.shp")
lineas_metro.head()

,SISTEMA,LINEA,RUTA,geometry
0,STC Metro,1,Observatorio - Pantitlàn,"LINESTRING Z (478958.079 2144909.693 0, 479222..."
1,STC Metro,2,Cuatro Caminos - Tasqueña,"LINESTRING Z (477345.656 2151695.912 0, 477344..."
2,STC Metro,3,Indios Verdes - Universidad,"LINESTRING Z (487459.272 2155641.308 0, 487436..."
3,STC Metro,4,Martín Carrera - Santa Anita,"LINESTRING Z (487222.685 2145411.999 0, 487225..."
4,STC Metro,5,Politecnico - Pantitlán,"LINESTRING Z (484343.637 2156234.759 0, 484375..."

In [46]:
lineas_metro.explore()

##### No requiró limpieza por lo que se exporta como se descargaron

In [47]:
lineas_metro.to_file("../datos/procesados/SCT_metro_limpia/lineas_metro.gpkg", driver = "GPKG")

### Estaciones

In [49]:
estaciones_metro = gpd.read_file(ruta_shp+"stcmetro_shp/STC_Metro_estaciones_utm14n.shp")
estaciones_metro.head()

,SISTEMA,NOMBRE,LINEA,EST,CVE_EST,CVE_EOD17,TIPO,ALCALDIAS,AÑO,geometry
0,STC Metro,Pantitlán,01,01,STC0101,05014,Terminal / Transbordo,Venustiano Carranza,1984,POINT Z (-99.07474 19.41633 0)
1,STC Metro,Zaragoza,01,02,STC0102,05020,Intermedia,Venustiano Carranza,1969,POINT Z (-99.08229 19.41192 0)
2,STC Metro,Gomez Farías,01,03,STC0103,05007,Intermedia,Venustiano Carranza,1969,POINT Z (-99.09021 19.41648 0)
3,STC Metro,Boulevard Puerto Aéreo,01,04,STC0104,05003,Intermedia,Venustiano Carranza,1969,POINT Z (-99.09626 19.41994 0)
4,STC Metro,Balbuena,01,05,STC0105,05001,Intermedia,Venustiano Carranza,1969,POINT Z (-99.10277 19.42336 0)

#### Limpieza de columnas

In [50]:
estaciones_metro_limpia = estaciones_metro[
    ["SISTEMA", "NOMBRE", "LINEA", "TIPO", "ALCALDIAS", "geometry"]
]

In [52]:
estaciones_metro_limpia.head()
estaciones_metro_limpia.explore()

In [53]:
estaciones_metro_limpia.to_file("../datos/procesados/SCT_metro_limpia/estaciones_metro_limpia.gpkg", driver = "GPKG")